"""The one writer: normalized model in, artifact out.

There is deliberately only one. qgis2web has two - a Leaflet family and an
OpenLayers family, ~7,500 lines between them - and every symbology fix has to be
made in both. Where it was not, the two diverged.

**Preview and export share this code path.** Issue #29 requires it and qgis2web
proves it works: if preview runs through a different renderer it can drift from
what actually ships, and the drift is invisible until a recipient complains.

Copyright (C) 2026 NIKA
SPDX-License-Identifier: GPL-2.0-or-later
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from ..core.export_ir import ExportProject, FidelityItem, OutputMode
from ..core.fidelity_report import FidelityReportBuilder
from ..core.license_policy import CapVerdict, LicensePolicy, default_policy
from ..core.manifest_builder import build_manifest
from ..packaging.asset_embedder import (
    build_bootstrap,
    gzip_base64,
    should_compress_data,
)
from ..packaging.dependency_scanner import ScanResult, scan
from ..packaging.runtime_manager import (
    RuntimeBundle,
    RuntimeProvider,
    default_provider,
)

TEMPLATE_PATH = Path(__file__).resolve().parent.parent / "templates" / "map.html"
PLUGIN_VERSION = "0.1.0"


class ExportBlockedError(RuntimeError):
    """The export cannot produce a working artifact.

    Raised only for genuinely unrecoverable conditions - nothing to export, a
    required asset missing. Licence-cap breaches are *not* in this category: they
    warn, and the map explains itself to the recipient.
    """

    def __init__(self, reasons: tuple[str, ...]) -> None:
        self.reasons = reasons
        super().__init__("; ".join(reasons))


@dataclass(frozen=True)
class ArtifactFile:
    path: Path
    size_bytes: int

    def snapshot(self) -> dict[str, Any]:
        return {"name": self.path.name, "sizeBytes": self.size_bytes}


@dataclass(frozen=True)
class ArtifactResult:
    """What a write produced. The shape issue #29 specifies.

    `manifest_snapshot` is the deterministic record: the same project written
    twice produces the same snapshot, which is what makes an export reproducible
    and a regression visible in a diff.
    """

    entry_path: Path
    mode: OutputMode
    files: tuple[ArtifactFile, ...] = ()
    runtime_version: str = "unknown"
    runtime_sha256: str = ""
    compressed: bool = False
    network_dependencies: tuple[str, ...] = ()
    fidelity: tuple[FidelityItem, ...] = ()
    warnings: tuple[str, ...] = ()
    manifest_snapshot: dict[str, Any] = field(default_factory=dict)

    @property
    def total_bytes(self) -> int:
        return sum(f.size_bytes for f in self.files)

    @property
    def is_offline(self) -> bool:
        """No network dependency means the artifact works with no internet."""
        return not self.network_dependencies

    def snapshot(self) -> dict[str, Any]:
        return {
            "entry": self.entry_path.name,
            "mode": self.mode.value,
            "files": [f.snapshot() for f in self.files],
            "runtimeVersion": self.runtime_version,
            "runtimeSha256": self.runtime_sha256,
            "compressed": self.compressed,
            "networkDependencies": list(self.network_dependencies),
            "fidelity": [i.snapshot() for i in self.fidelity],
            "warnings": list(self.warnings),
            "manifest": self.manifest_snapshot,
        }


def generator_line(runtime: RuntimeBundle, when: datetime | None = None) -> str:
    """The provenance comment placed at the top of every artifact.

    Written for two readers. A person wants to know what made this and when; an
    AI assistant asked to modify the file wants to know which runtime version's
    attribute vocabulary applies.
    """
    stamp = (when or datetime.now(timezone.utc)).strftime("%Y-%m-%d %H:%M UTC")
    return (
        f"Generated by QGIS2WebMap by NIKA {PLUGIN_VERSION} on {stamp}\n"
        f"  OnlyMap runtime {runtime.version} (sha256 {runtime.sha256[:16]}...)\n"
        "  Contains no tracking and makes no network requests."
    )


class OnlyMapWriter:
    """Builds an OnlyMap artifact from a normalized project."""

    def __init__(
        self,
        runtime_provider: RuntimeProvider | None = None,
        license_policy: LicensePolicy | None = None,
    ) -> None:
        self.runtime_provider = runtime_provider or default_provider()
        self.license_policy = license_policy or default_policy()

    def render_html(
        self,
        project: ExportProject,
        runtime: RuntimeBundle,
        verdict: CapVerdict,
        when: datetime | None = None,
        compress: bool = True,
        compress_data: bool = False,
        preview_hook: str = "",
    ) -> str:
        """Fill the artifact template. No string-built HTML beyond the manifest."""
        template = TEMPLATE_PATH.read_text(encoding="utf-8")
        manifest = build_manifest(project, verdict, compress_data=compress_data)

        if compress:
            # Gzipped base64 plus a bootstrap that inflates it. Roughly a third
            # of the raw size, and nobody edits minified runtime code anyway.
            script_body = build_bootstrap(gzip_base64(runtime.javascript))
        else:
            script_body = runtime.javascript.decode("utf-8")

        # Replacement, not format(): the template is full of CSS braces, and
        # str.format would choke on every one of them.
        replacements = {
            "@GENERATOR@": generator_line(runtime, when),
            "@TITLE@": _escape_text(project.title),
            "@MANIFEST@": manifest,
            # Never compressed: the fallback's CSS gate must work without JS.
            "@RUNTIME_CSS@": runtime.css.decode("utf-8"),
            "@RUNTIME_JS@": script_body,
            "@PREVIEW_HOOK@": preview_hook,
        }

        # One pass, not a loop of replaces. Substituting sequentially would let
        # earlier-inserted content be scanned again: a layer named
        # "@RUNTIME_JS@" would have five megabytes of runtime pasted into its
        # label. A single regex pass can only ever match the template's own
        # tokens.
        pattern = re.compile("|".join(re.escape(t) for t in replacements))
        return pattern.sub(lambda m: replacements[m.group(0)], template)

    def write(
        self,
        project: ExportProject,
        destination: Path,
        mode: OutputMode = OutputMode.STANDALONE_HTML,
        when: datetime | None = None,
        compress: bool = True,
        preview_hook: str = "",
    ) -> ArtifactResult:
        """Write the artifact and describe what was produced.

        `destination` is a directory; the entry file is always `index.html` so a
        recipient never has to guess which file to open.

        Scanning happens first: an export that cannot work for its recipient
        should fail before anything is written, not after.
        """
        runtime = self.runtime_provider.load()
        verdict = self.license_policy.evaluate(project)

        scan_report = FidelityReportBuilder()
        scan_result: ScanResult = scan(project, scan_report, mode)
        if not scan_result.can_export:
            raise ExportBlockedError(scan_result.blocking_reasons)

        # Small maps keep readable data so a person or an agent can edit them.
        compress_data = compress and should_compress_data(scan_result.data_bytes)

        destination.mkdir(parents=True, exist_ok=True)
        entry = destination / "index.html"
        entry.write_text(
            self.render_html(
                project,
                runtime,
                verdict,
                when,
                compress,
                compress_data,
                preview_hook,
            ),
            encoding="utf-8",
        )

        warnings = [v.detail for v in verdict.violations]
        if project.settings.has_lossy_transform:
            warnings.append(
                "A lossy transform was applied, so the exported coordinates are "
                "less precise than the source data."
            )

        return ArtifactResult(
            entry_path=entry,
            mode=mode,
            files=(ArtifactFile(entry, entry.stat().st_size),),
            runtime_version=runtime.version,
            runtime_sha256=runtime.sha256,
            compressed=compress,
            network_dependencies=scan_result.remote_dependencies,
            fidelity=project.fidelity + scan_report.items,
            warnings=tuple(warnings),
            manifest_snapshot=project.snapshot(),
        )


def _network_dependencies(project: ExportProject) -> tuple[str, ...]:
    """Anything the finished map would fetch when opened.

    Empty is the goal and the default: no basemap, data inlined, telemetry off.
    A non-empty result contradicts the promise in the README and should be
    surfaced, not quietly tolerated.
    """
    remote: list[str] = []
    for layer in project.layers:
        for dependency in layer.dependencies:
            if dependency.disposition.value == "remote":
                remote.append(dependency.identifier)
    return tuple(remote)


def _escape_text(value: str) -> str:
    """Escape for HTML text content (the title appears in <title> and a footer)."""
    return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
