#!/usr/bin/env python3
"""Write the documentation site's analytics key into a Jekyll data file.

    python scripts/configure_site.py

Reads `POSTHOG_KEY` (and optionally `POSTHOG_HOST`) from the environment and
writes `docs/_data/posthog.yml`. Unset, it removes that file and says so: a site
built from a clean checkout measures nothing, which is what a local
`jekyll serve` should do.

The Pages workflow supplies the key from a repository secret, which is the only
place it is configured. There is deliberately no dotenv file to fall back to -
the site is not meant to report from a laptop, and the one time that is wanted
(reproducing a production analytics problem) the environment does it in one
line:

    POSTHOG_KEY=phc_... python scripts/configure_site.py

**`_data/` rather than `_config.yml` on purpose.** Jekyll loads everything in
`_data/` automatically, with no extra flag, so this works under
`actions/jekyll-build-pages` - which accepts no `--config` argument - without
this script having to rewrite a tracked file. The generated file is gitignored,
so the key cannot be committed by accident.

**The key is not a secret and is not treated as one.** A PostHog `phc_` project
key is write-only and ships in the page source of every published page; anyone
may read it. Keeping it out of the repository avoids tripping secret scanners
during plugin-repository review and allows rotation without a commit. It buys
nothing else, so do not build anything on the assumption that it is hidden.

Copyright (C) 2026 NIKA
SPDX-License-Identifier: GPL-2.0-or-later
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_FILE = REPO_ROOT / "docs" / "_data" / "posthog.yml"

DEFAULT_HOST = "https://us.i.posthog.com"


def resolve(name: str, default: str = "") -> str:
    """The environment variable, or the default if it is unset or blank.

    An unset repository secret arrives as the empty string rather than as an
    absent variable, so blank has to mean the same as missing - otherwise a fork
    building without the secret would write an empty key into the data file and
    the site would try to initialise analytics with it.
    """
    return os.environ.get(name, "").strip() or default


def main() -> int:
    key = resolve("POSTHOG_KEY")
    host = resolve("POSTHOG_HOST", DEFAULT_HOST)

    if not key:
        if DATA_FILE.exists():
            DATA_FILE.unlink()
        print("POSTHOG_KEY not set: site analytics disabled, no data file written")
        return 0

    if not key.startswith("phc_"):
        # The write-only project key is the only one that belongs here. A
        # personal API key (`phx_`) would be a real secret and must never be
        # published into the page source, so refuse rather than ship it.
        print(
            f"POSTHOG_KEY does not look like a project key (expected phc_..., got "
            f"{key[:4]}...): refusing to write it",
            file=sys.stderr,
        )
        return 1

    DATA_FILE.parent.mkdir(parents=True, exist_ok=True)
    DATA_FILE.write_text(
        "# Generated by scripts/configure_site.py - do not commit, do not edit.\n"
        f"key: {key}\n"
        f"host: {host}\n",
        encoding="utf-8",
    )
    print(f"wrote {DATA_FILE.relative_to(REPO_ROOT)} (host {host})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
