#!/usr/bin/env python3
"""Write the documentation site's analytics key into a Jekyll data file.

    python scripts/configure_site.py

Reads `POSTHOG_KEY` (and optionally `POSTHOG_HOST`) from the environment,
falling back to a `.env.local` file in the repository root, and writes
`docs/_data/posthog.yml`. With neither set it removes that file and says so:
a site built from a clean checkout measures nothing, which is what a local
`jekyll serve` should do.

**`_data/` rather than `_config.yml` on purpose.** Jekyll loads everything in
`_data/` automatically, with no extra flag, so this works under
`actions/jekyll-build-pages` - which accepts no `--config` argument - without
this script having to rewrite a tracked file. The generated file is gitignored,
so the key cannot be committed by accident.

**The key is not a secret and is not treated as one.** A PostHog `phc_` project
key is write-only and ships in the page source of every published page; anyone
may read it. Keeping it out of the repository avoids tripping secret scanners
during plugin-repository review and allows rotation without a commit. It buys
nothing else, so do not build anything on the assumption that it is hidden.

Copyright (C) 2026 NIKA
SPDX-License-Identifier: GPL-2.0-or-later
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = REPO_ROOT / ".env.local"
DATA_FILE = REPO_ROOT / "docs" / "_data" / "posthog.yml"

DEFAULT_HOST = "https://us.i.posthog.com"


def read_env_file(path: Path) -> dict[str, str]:
    """Parse the `KEY=value` lines of a dotenv file, ignoring comments.

    Deliberately minimal - no quoting rules, no interpolation, no export
    keyword. The file holds two flat values and adding a dependency to read
    them would cost more than it explains.
    """
    if not path.is_file():
        return {}

    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        name, _, value = stripped.partition("=")
        values[name.strip()] = value.strip().strip("\"'")
    return values


def resolve(name: str, from_file: dict[str, str], default: str = "") -> str:
    """Environment first, then `.env.local`, then the default.

    Environment wins so CI - which has no `.env.local` - can pass the key in
    from a repository secret, and so a one-off local build can override the
    file without editing it.
    """
    from_env = os.environ.get(name, "").strip()
    return from_env or from_file.get(name, "").strip() or default


def main() -> int:
    from_file = read_env_file(ENV_FILE)
    key = resolve("POSTHOG_KEY", from_file)
    host = resolve("POSTHOG_HOST", from_file, DEFAULT_HOST)

    if not key:
        if DATA_FILE.exists():
            DATA_FILE.unlink()
        print("POSTHOG_KEY not set: site analytics disabled, no data file written")
        return 0

    if not key.startswith("phc_"):
        # The write-only project key is the only one that belongs here. A
        # personal API key (`phx_`) would be a real secret and must never be
        # published into the page source, so refuse rather than ship it.
        print(
            f"POSTHOG_KEY does not look like a project key (expected phc_..., got "
            f"{key[:4]}...): refusing to write it",
            file=sys.stderr,
        )
        return 1

    DATA_FILE.parent.mkdir(parents=True, exist_ok=True)
    DATA_FILE.write_text(
        "# Generated by scripts/configure_site.py - do not commit, do not edit.\n"
        f"key: {key}\n"
        f"host: {host}\n",
        encoding="utf-8",
    )
    print(f"wrote {DATA_FILE.relative_to(REPO_ROOT)} (host {host})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
