"""The same project exported twice has to produce the same bytes.

A ring-1 requirement rather than a nicety, and it is one the architecture
document states in those terms. Content-addressed publishing is built on it:
the server stores every asset under its digest and short-circuits a republish
whose manifest digest has not moved, so anything that drifts between two
exports of one project turns every republish into a full upload and makes the
"nothing changed" path unreachable.

The document names the usual culprits - a build timestamp in the generator
line, non-deterministic dict or set ordering, a UUID minted per export, float
formatting - and the first of them was real: the page carried
`Generated by ... on 2026-09-11 04:32 UTC`, so two exports a minute apart
disagreed. See `generator_line` for what changed and why the offline tiers
still stamp.

**Every file, not just the page.** A stable page over a shifting `.geojson`
would pass a narrower test and still break dedup for the payload that is
actually large. So each digest is compared, and the manifest with them.

Copyright (C) 2026 NIKA
SPDX-License-Identifier: GPL-2.0-or-later
"""

from __future__ import annotations

import hashlib
import json
import re
from datetime import datetime, timezone
from pathlib import Path

from test_hosted_output import FakeRuntime, make_project, realistic_project

from nika_onlymap_exporter.core.export_ir import OutputMode
from nika_onlymap_exporter.packaging.publish_manifest import build_publish_manifest
from nika_onlymap_exporter.writers.onlymap_writer import OnlyMapWriter

# Clocks far enough apart that any timestamp at any resolution would differ.
# Exported artifacts are compared across them, so a stamp anywhere in the bytes
# fails this file rather than showing up as a re-upload nobody notices.
CLOCKS = (
    datetime(2026, 1, 2, 3, 4, tzinfo=timezone.utc),
    datetime(2026, 1, 2, 3, 5, tzinfo=timezone.utc),
    datetime(2031, 7, 9, 13, 37, tzinfo=timezone.utc),
    None,  # the real clock, which is what a user's export actually uses
)

# A timestamp as the banner used to spell one. Matched rather than searched for
# literally, so a reformatted stamp is caught too.
STAMP_PATTERN = re.compile(r"\d{4}-\d{2}-\d{2} \d{2}:\d{2} UTC")


def export_hosted(destination: Path, project, when: datetime | None) -> dict[str, str]:
    """One hosted export, reduced to what the server keys on: name -> digest."""
    OnlyMapWriter(runtime_provider=FakeRuntime()).write(
        project, destination, hosted=True, when=when
    )
    return {
        path.name: hashlib.sha256(path.read_bytes()).hexdigest()
        for path in sorted(destination.iterdir())
    }


def manifest_digest(directory: Path) -> str:
    """The manifest reduced the same way. Sorted keys, because this is a
    comparison of content and not of serialisation order."""
    manifest = build_publish_manifest(directory)
    return hashlib.sha256(
        json.dumps(manifest, sort_keys=True).encode("utf-8")
    ).hexdigest()


class TestHostedExportIsReproducible:
    def test_four_exports_across_four_clocks_are_byte_identical(self, tmp_path) -> None:
        """Four rather than two on purpose.

        A pair of exports agrees by luck often enough to be worth guarding
        against: iteration order over a set is stable within one process, so a
        set that reached the output would pass a two-export comparison and fail
        in the field, where the two exports are two different runs. Comparing
        several exports made from separately constructed projects is what makes
        an ordering bug show up here.
        """
        runs = []
        for index, clock in enumerate(CLOCKS):
            directory = tmp_path / f"run-{index}"
            digests = export_hosted(directory, realistic_project(), clock)
            runs.append((digests, manifest_digest(directory)))

        first = runs[0]
        assert first[0], "the export produced no files at all"
        for other in runs[1:]:
            assert other == first

    def test_the_page_carries_no_build_timestamp(self, tmp_path) -> None:
        """The specific defect, asserted where it happened.

        The equality test above would catch a stamp only while the clock in the
        test moved. This catches one whose resolution is coarse enough to be
        identical across a test run and different across a working week.
        """
        export_hosted(tmp_path, realistic_project(), CLOCKS[0])
        page = (tmp_path / "index.html").read_text(encoding="utf-8")
        assert not STAMP_PATTERN.search(page)
        # Provenance is not what was dropped - only the clock reading.
        assert "Generated by QGIS2WebMap by NIKA" in page

    def test_the_manifest_still_says_what_produced_the_release(self, tmp_path) -> None:
        """What replaces the banner's timestamp: the producer in the manifest,
        and a publication time the server records from its own clock."""
        export_hosted(tmp_path, realistic_project(), CLOCKS[0])
        manifest = build_publish_manifest(tmp_path)
        assert manifest["producer"]["name"] == "qgis2webmap"
        assert manifest["producer"]["version"]
        assert manifest["runtime"]["version"]

    def test_an_unchanged_project_reuses_every_asset(self, tmp_path) -> None:
        """The property dedup actually depends on, stated as itself.

        The server uploads only digests it does not already hold, so a
        republish of an unchanged project should ask it to store nothing.
        """
        first = export_hosted(tmp_path / "a", realistic_project(), CLOCKS[0])
        second = export_hosted(tmp_path / "b", realistic_project(), CLOCKS[2])
        assert set(second.values()) <= set(first.values())


class TestOfflineTiersStillStamp:
    """The asymmetry is deliberate; see `generator_line`."""

    def test_a_single_file_export_keeps_the_build_timestamp(self, tmp_path) -> None:
        result = OnlyMapWriter(runtime_provider=FakeRuntime()).write(
            make_project(), tmp_path, compress=False, when=CLOCKS[0]
        )
        page = result.entry_path.read_text(encoding="utf-8")
        assert STAMP_PATTERN.search(page)

    def test_a_folder_export_keeps_it_too(self, tmp_path) -> None:
        result = OnlyMapWriter(runtime_provider=FakeRuntime()).write(
            make_project(),
            tmp_path,
            mode=OutputMode.FOLDER,
            compress=False,
            unbundle=True,
            when=CLOCKS[0],
        )
        page = result.entry_path.read_text(encoding="utf-8")
        assert STAMP_PATTERN.search(page)
